document_distribution/document_distribution/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls')),
    path('file/', include('files.urls')),
    path('api/', include('rest_api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document_distribution/files/urls.py
from django.urls import path
from . import views

app_name = "files"

urlpatterns = [
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("file-upload", views.UploadFile.as_view(), name="file-upload"),
    path('delete/<int:pk>/', views.DeleteFileView.as_view(), name="delete"),
    path('download/<int:pk>/', views.DownloadFileView.as_view(), name="download"),
    path('account', views.AccounView.as_view(), name="account"),
    path('change-password', views.ChangePasswordView.as_view(), name="change-password"),
    path("user-dashboard", views.UserDashboard.as_view(), name="user-dashboard"),
    path("user-account", views.UserAccounView.as_view(), name="user-account"),
    path("search-file", views.SearchView.as_view(), name="search-file"),
    path("send-file-via-email/<int:pk>/", views.SendFileViaEmail.as_view(), name="send-file-via-email"),
  
]

document_distribution/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("register", views.Register.as_view(), name="register"),
    path("verify", views.CodeVerificationView.as_view(), name="verify"),
    path("log-out", views.LogoutView.as_view(), name="log-out"),
    path("reset_password", views.ResetPasswordView.as_view(), name="reset_password"),
    path("password_reset_done", views.PasswordResetDone.as_view(), name="password_reset_done"),
    path("delete-account", views.DeleteAccount.as_view(), name="delete-account"),
]

document_distribution/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.managers import CustomUserManager

# Create your models here.

"""Models for user creation"""
class User(AbstractUser):
    email_address = models.EmailField(
        verbose_name='email', max_length=200, unique=True)
    

    USERNAME_FIELD = 'email_address'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.email_address
    
"""Code email model for temporary storing users until they verified their account"""
class CodeEmail(models.Model):
    code = models.IntegerField()
    email_address = models.EmailField(max_length=254, unique=True,blank=False)
    password = models.CharField(max_length=200, blank=True, unique=False,null=True)
    updated_at= models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ("email_address",)
        
    def __str__(self):
        return self.email_address

document_distribution/rest_api/views/user.py
from django.shortcuts import render
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django.contrib.auth import authenticate
from rest_framework import status
from rest_framework import generics, permissions
from rest_framework_simplejwt.tokens import RefreshToken
from rest_api.serialiers.user_serializers import *
from utils.function import *
from django.contrib.auth import get_user_model
from users.models import *
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
import re
User = get_user_model()
# Create your views here.


def get_auth_for_user(user):
    refresh = RefreshToken.for_user(user)
    return {
        'user':UserLoginSerializer(user).data,
        'permission':get_all_user_permissions(user),
        'refresh': str(refresh),
        'token': str(refresh.access_token) 
    }
    
    
class SignInAPI(generics.GenericAPIView):
    permission_classes = [permissions.AllowAny]
    serializer_class = CodeEmailSerializer
    def post(self, request,*args, **kwargs):
        serializers = self.serializer_class(data=request.data)
        if serializers.is_valid():
            email_address = serializers.data["email_address"]
            password = serializers.data["password"]
            if User.objects.filter(email_address=email_address): 
                user = authenticate(email_address=email_address,password=password)
                if not user:
                    response_data = {'message':'Invalid Credential'}
                    return Response(response_data, status=400)
                
                user_data = get_auth_for_user(user)
                return Response(user_data, status=200)
            else:
                return Response(
                    {
                        "status": "error",
                        "detail": "User Not Found",
                    },
                    status=404,
                )
        else:
            return Response(
                {"status": "failure", "detail": serializers.errors},
                status=status.HTTP_400_BAD_REQUEST,
            )

class RegistrationAPI(generics.GenericAPIView):
    permission_classes = [permissions.AllowAny]
    serializer_class = CodeEmailSerializer
    def post(self, request,*args, **kwargs):
        serializers = self.serializer_class(data=request.data)
        if serializers.is_valid():
            email_address = serializers.data["email_address"]
            password = serializers.data["password"]
            # Validate password
            if len(password) < 4:
                return Response(
                    {"status": "failure", "detail": "Password Must be at least 4 characters"},
                    status=400,
                )
        
            # Validate email address format
            if not re.match(r"[^@]+@[^@]+\.[^@]+", email_address):
                return Response(
                    {"status": "failure", "detail": "Invalid email address format"},
                    status=400,
                )
            
            if User.objects.filter(email_address=email_address):
                return Response(
                    {"status": "failure", "detail": "Email Already Exist"},
                    status=400,
                )

            if CodeEmail.objects.filter(email_address=email_address):
                code_user = CodeEmail.objects.get(email_address=email_address)
                generated_code = generate_activation_code()
                code_user.code = generated_code
                code_user.save()
                context = {
                "generated_code": generated_code,
                }
                html_message = render_to_string("user/verify.html",context)
                plain_message = strip_tags(html_message)
                try:
                    message = EmailMultiAlternatives(
                    subject="Email Verification Code",
                    body=plain_message,
                    from_email=settings.EMAIL_HOST_USER,
                    to=[email_address],
                )
                    message.attach_alternative(html_message, 'text/html')
                    message.send()
                    return Response(
                        {
                            "status": "success",
                            "detail": "email verification code send",
                            "data": {
                                "email_address": email_address,
                            },
                        },
                        status=status.HTTP_200_OK,
                    )
                except Exception as e:
                    return Response(
                        {
                            "status": "error",
                            "detail": f"Error sending email: {e}, try again",
                        },
                        status=400,
                    )
            # Generate Verification Code
            generated_code = generate_activation_code()
            context = {
                "generated_code": generated_code,
            }
            html_message = render_to_string("user/verify.html",context)
            plain_message = strip_tags(html_message)
            
            code_user = CodeEmail.objects.create(email_address=email_address, password=password,code=generated_code)
            code_user.save()
            # Send Email with verification Code  to User Email 
            try:
                message = EmailMultiAlternatives(
                subject="Email Verification Code",
                body=plain_message,
                from_email=settings.EMAIL_HOST_USER,
                to=[email_address],
                )
                message.attach_alternative(html_message, 'text/html')
                message.send()
                return Response(
                    {
                        "status": "success",
                        "detail": "email verification code send",
                        "data": {
                            "email_address": email_address,
                        },
                    },
                    status=status.HTTP_201_CREATED,
                )
            except Exception as e:
                return Response(
                    {
                        "status": "error",
                        "detail": f"Error sending email: {e}, try again",
                    },
                    status=400,
                )
        else:
            return Response(
                {"status": "failure", "detail": serializers.errors},
                status=status.HTTP_400_BAD_REQUEST,
            )


class EmailVerificationAPI(generics.GenericAPIView):
    permission_classes = [permissions.AllowAny]
    def post(self, request, *args, **kwargs):
        code = request.data.get("code")
        if not code:
            return Response(
                {
                    "status": "error",
                    "detail":"the code is required",
                },
                status=400,
            )
        # Check if code is not numeric
        if not code.isdigit():
            return Response(
                {
                    "status": "error",
                    "detail": "The code must be numeric",
                },
                status=400,
            )
        try:
            code_email = CodeEmail.objects.get(code=code)
            user = User.objects.create_user(username=code_email.email_address, email_address=code_email.email_address, password=code_email.password)
            user.save()
            code_email.delete()
            user_data = get_auth_for_user(user)
            return Response(user_data, status=200)           
        except CodeEmail.DoesNotExist:
            return Response(
                {
                    "status": "error",
                    "detail":"Invalid or Wrong Code Entered",
                },
                status=400,
            )
    
class LogOutAPI(generics.GenericAPIView):
    """Logout API view to blacklist refresh token"""

    permission_classes = [permissions.IsAuthenticated]
    def post(self, request):
        try:
            refresh_token = request.data["refresh"]
            token = RefreshToken(refresh_token)
            token.blacklist()
            return Response({"detail": "Successfully logged out."}, status=200)
        except Exception as e:
            return Response({"detail": f"Error logging out. {e}"}, status=400)

class ChangePasswordAPI(generics.GenericAPIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = ChangePasswordSerializer
    def post(self, request, *args, **kwargs):
        """For changing password"""
        user = request.user
        serializers = self.serializer_class(data=request.data)
        if serializers.is_valid():
            current_password = serializers.data["current_password"]
            new_password = serializers.data["new_password"]
            
            if len(new_password) < 4:
                return Response(
                    {"status": "failure", "detail": "Password Must be at least 4 characters"},
                    status=400,
                )
            try:
                if not user.check_password(current_password):
                    return Response(
                        {
                            "status": "failure",
                            "detail": "wrong current password",
                        },
                        status=status.HTTP_400_BAD_REQUEST,
                    )
                else:
                    user.set_password(new_password)
                    user.save()
                    return Response(
                        {
                            "status": "success",
                            "detail": "Password changed successfully",

document_distribution/templates/user/account.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Settings</title>
    <link rel="stylesheet" href="{% static 'css/settings.css'%}" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}" />
</head>

<body>
    <header class="top-nav">
        <div>
            <img src="{% static 'assets/icons/logo.svg'%}" alt="chuck it logo" class="logo" />
        </div>
        <div class="user">
            <small>{{user.email_address}}</small>
            <img src="{% static 'assets/icons/logout-icon.png'%}" alt="" onclick="toggleLogoutModal()" />
        </div>
    </header>
    <main>
        <section class="backdrop"></section>
        <nav class="nav-drawer">
            <div class="top">
                <img src="{% static 'assets/icons/menu.png'%}" alt="" class="hamburger" />
                <img src="{% static 'assets/icons/logo.svg'%}" alt="chunck it logo" class="logo" />
            </div>
            <ul class="navigation">
                <li>
                    <a href="{% url 'files:user-dashboard' %}">
                        <img src="{% static 'assets/icons/Folder-filled.png'%}" alt="" />
                        <small>Library</small>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'files:user-account' %}">
                        <img src="{% static 'assets/icons/manage_accounts.png'%}" alt="" />
                        <small>Account</small>
                    </a>
                </li>

            </ul>

            <small class="copy-right"><strong>&copy; 2024, Inc</strong></small>
        </nav>
        <form class="modal" id="delete-account-modal" action="{% url 'users:delete-account' %}" method="post">
            {% csrf_token %}
            <div class="modal-content">
                <h2>Delete Account</h2>
                <p>
                    Are you sure you want to delete your account? All saved files will
                    be lost forever.
                </p>
                <input type="hidden" name="user_id" value="{{user.id}}">
                <button class="btn-danger" type="submit">Delete Acount</button>
                <button type="button" class="cancel">Cancel</button>
            </div>
        </form>
        <section class="modal" id="logout-modal">
            <div class="modal-content">
                <h2>Log out</h2>
                <p>Are you sure you want to log out?</p>
                <button class="btn-danger"><a href="{% url 'users:log-out' %}"
                        style="cursor: pointer; color:inherit; text-decoration: none;">Log
                        out</a></button>
                <button class="cancel">Cancel</button>
            </div>
        </section>
        <section class="settings">
            <div class="account">
                <div class="info">
                    <h4>Account</h4>
                    <p>Email: {{user.email_address}}</p>
                </div>
                {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    {% if message.tags == "success"%}
                    <p style="color: rgb(37, 195, 135);">{{message}}</p>
                    {% else %}
                    <p style="color: red;">{{message}}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <div class="change-password">
                    <h4>Change password</h4>
                    <span><img src="{% static 'assets/icons/keyboard_arrow_down.svg'%}" alt="" /></span>
                    <form action="{% url 'files:change-password' %}" method="post">
                        {% csrf_token %}
                        <div class="form-control">
                            <label for="current-password">Current password</label>
                            <input type="password" name="current" id="current-password" placeholder="Password" />
                            <img class="" id="toggle-current-password"
                                src="{% static 'assets/icons/remove_red_eye.png'%}" alt="show password icon" />
                        </div>
                        <div class="form-control">
                            <label for="new-password">New password</label>
                            <input type="password" name="new_password" id="new-password" placeholder="Password" />
                            <img class="" id="toggle-new-password" src="{% static 'assets/icons/remove_red_eye.png'%}"
                                alt="show password icon" />
                        </div>
                        <div class="form-action">
                            <button>Save New Password</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="right">
                <div>
                    <img src="{% static 'assets/images/Settings-panel.png'%}" alt="settings image" />
                </div>
                <div class="account-action">
                    <button class="btn-danger">
                        <span><img src="{% static 'assets/icons/delete-icon-light.png'%}" alt="" /></span>
                        Delete Account
                    </button>
                </div>
            </div>
        </section>
    </main>
    <script src="{% static 'js/settings.js'%}"></script>
    <script>
        // Function to remove error messages after 5 seconds
        setTimeout(function() {
            var alertMessages = document.querySelectorAll('.alert');
            alertMessages.forEach(function(alert) {
                alert.remove();
            });
        }, 5000);
    </script>
</body>

</html>

document_distribution/templates/user/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- <link rel="stylesheet" href="index.css" /> -->
    <link rel="stylesheet" href="{% static 'css/dashboard-modal.css'%}" />
    <link rel="stylesheet" href="{% static 'css/saved-files.css'%}" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}" />
</head>

<body>
    <header class="top-nav">
        <div>
            <img src="{% static 'assets/icons/logo.svg'%}" alt="chuck it logo" class="logo" />
        </div>
      
        <form method="post" action="{% url 'files:search-file' %}" class="search">
            {% csrf_token %}
            <div style="display: flex; gap:10px">
                
                <input type="search"  name="keyword" placeholder="search for file here...">
                <button class="btn-upload" type="submit"> Search </button>
                    
            </div>
        
        </form>
        
        <div class="user" style="margin-top: -20px;">
            <small>{{user.email_address}}</small>
            <a href="{% url 'users:log-out' %}"><img src="{% static 'assets/icons/logout-icon.png'%}" alt=""
                    style="cursor: pointer;" /></a>
        </div>
    </header>
    <main>
        
        <section class="backdrop"></section>
        <nav class="nav-drawer">
            <div class="top">
                <img src="{% static 'assets/icons/menu.png'%}" alt="" class="hamburger" />
                <img src="{% static 'assets/icons/logo.svg'%}" alt="chunck it logo" class="logo" />
            </div>

            <ul class="navigation">
                <li class="active">
                    <a href="{% url 'files:user-dashboard' %}">
                        <img src="{% static 'assets/icons/Folder-filled.png'%}" alt="" />
                        <small>Library</small>
                    </a>
                </li>
                <li>
                    <a href="{% url 'files:user-account' %}">
                        <img src="{% static 'assets/icons/manage_accounts.png'%}" alt="" />
                        <small>Account</small>
                    </a>
                </li>
            </ul>

            <small class="copy-right"><strong>&copy; 2024, Inc</strong></small>
        </nav>
        
        {% if files %}
        <section class="saved-files">
            <h1> Search Result(s) for  <span style="color: #301e4e;"> {{request.POST.keyword}} </span> </h1>
            <table style="margin: 20px;">
                <thead>
                    <tr>
                        <th scope="col">File Title</th>
                        <th scope="col">Type</th>
                        <th scope="col">Description</th>
                        <th scope="col">Last Modified</th>
                        <th scope="col">Actions</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for file in files %}
                   
                    <tr>
                        <td>{{file.title}}</td>
                        <td>{{file.type}}</td>
                        <td>
                            <textarea style="border: none; resize: none;" rows="2" cols="40" readonly>{{ file.description }}</textarea>
                        </td>
                        <td>
                            <span class="date">{{file.created_at}}</span>
                        </td>
                       
                        <td>
                            <div>
                                <button class="btn-download">
                                    <a href="{% url 'files:download' file.id %}" ><img
                                            src="{% static 'assets/icons/file_download.png'%}" alt="" /></a>
                                </button>
                                <button class="btn-delete">
                                    <a href=""><img
                                            src="{% static 'assets/icons/delete-icon-dark.png'%}" alt="" /></a>
                                </button>
                            </div>
                        </td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </section>
        {% else %}
        <section class="page-content">
            <img src="{% static 'assets/images/image.png'%}" alt="download folder image" />
            <p>Sorry, no result(s) found for  <span style="color: #301e4e;"> {{request.POST.keyword}}</span></p>
        </section>
        {% endif %}
    </main>
    

    <script src="{% static 'js/saved-files.js'%}"></script>
    <script src="{% static 'js/dashboard.js'%}"></script>
    
    <script>
        // Function to remove error messages after 5 seconds
        setTimeout(function() {
            var alertMessages = document.querySelectorAll('.alert');
            alertMessages.forEach(function(alert) {
                alert.remove();
            });
        }, 7000);
    </script>
</body>

</html>

document_distribution/templates/user/user_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- <link rel="stylesheet" href="index.css" /> -->
    <link rel="stylesheet" href="{% static 'css/dashboard-modal.css'%}" />
    <link rel="stylesheet" href="{% static 'css/saved-files.css'%}" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}" />
</head>

<body>
    <header class="top-nav">
        <div>
            <img src="{% static 'assets/icons/logo.svg'%}" alt="chuck it logo" class="logo" />
        </div>
      
        <form method="post" action="{% url 'files:search-file' %}" class="search">
            {% csrf_token %}
            <div style="display: flex; gap:10px">
                
                <input type="search"  name="keyword" placeholder="search for file here...">
                <button class="btn-upload" type="submit"> Search </button>      
            </div>
        </form>
        
        <div class="user" style="margin-top: -20px;">
            <small>{{user.email_address}}</small>
            <a href="{% url 'users:log-out' %}"><img src="{% static 'assets/icons/logout-icon.png'%}" alt=""
                    style="cursor: pointer;" /></a>
        </div>
    </header>
    <main>
        
        <section class="backdrop"></section>
        <nav class="nav-drawer">
            <div class="top">
                <img src="{% static 'assets/icons/menu.png'%}" alt="" class="hamburger" />
                <img src="{% static 'assets/icons/logo.svg'%}" alt="chunck it logo" class="logo" />
            </div>

            <ul class="navigation">
                <li class="active">
                    <a href="{% url 'files:user-dashboard' %}">
                        <img src="{% static 'assets/icons/Folder-filled.png'%}" alt="" />
                        <small>Library</small>
                    </a>
                </li>
                <li>
                    <a href="{% url 'files:user-account' %}">
                        <img src="{% static 'assets/icons/manage_accounts.png'%}" alt="" />
                        <small>Account</small>
                    </a>
                </li>
            </ul>

            <small class="copy-right"><strong>&copy; 2024, Inc</strong></small>
        </nav>
        
        {% if files %}
        <section class="saved-files">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {% if message.tags == "success"%}
                <p style="color: rgb(37, 195, 135);">{{message}}</p>
                {% else %}
                <p style="color: red;">{{message}}</p>
                {% endif %}
            </div>
            {% endfor %}
            <table>
                <thead>
                    <tr>
                        <th scope="col">File Title</th>
                        <th scope="col">Type</th>
                        <th scope="col">Description</th>
                        <th scope="col">Last Modified</th>
                        <th scope="col">download File</th>
                        <th scope="col">Email File</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for file in files %}
                   
                    <tr>
                        <td>{{file.title}}</td>
                        <td>{{file.type}}</td>
                        <td>
                            <textarea style="border: none; resize: none;" rows="2" cols="40" readonly>{{ file.description }}</textarea>
                        </td>
                        <td>
                            <span class="date">{{file.created_at}}</span>
                        </td>
                       
                        <td>
                            <div>
                                <button class="btn-download">
                                    <a href="{% url 'files:download' file.id %}" ><img
                                            src="{% static 'assets/icons/file_download.png'%}" alt="" /></a>
                                </button>
                            </div>
                        </td>
                        <td>
                            <div>
                                <button class="btn-delete">
                                    <a href="{% url 'files:send-file-via-email' file.id %}"><img style="width: 50%; height:50%"
                                            src="{% static 'assets/icons/send.png'%}" alt="" /></a>
                                </button>
                            </div>
                        </td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </section>
        {% else %}
        <section class="page-content">
            <img src="{% static 'assets/images/image.png'%}" alt="download folder image" />
            <p>The library is empty.</p>
            <p>Login as Admin to upload file</p>
            <p>Email:admin@gmail.com</p>
            <p>password:123</p>
        </section>
        {% endif %}
    </main>
    

    <script src="{% static 'js/saved-files.js'%}"></script>
    <script src="{% static 'js/dashboard.js'%}"></script>
    
    <script>
        // Function to remove error messages after 5 seconds
        setTimeout(function() {
            var alertMessages = document.querySelectorAll('.alert');
            alertMessages.forEach(function(alert) {
                alert.remove();
            });
        }, 7000);
    </script>
</body>

</html>